### ISSUE TITLE
이슈탭 사용해보기

### ISSUE THREAD

**Issue by GHooN99** [Palllang/simulation#4]
앞으로 할일을  투두리스트 같이 적어놓던가 
버그가 생겨서 해결해야 될 문제이거나

풀리퀘스트랑 이슈랑 연결 시켜서 머지되면 자동으로 이슈를 닫게 할 수도 있고 
뭔가 할일 목록처럼 사용 해보면 또 좋을거 같다는 생각이 드네요 ㅎㅎ

**Comment by Jiyajiwon** [comment]
우왕 네넵!
